config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'bowls#index', as: :authenticated_root
  end

  root 'home#index' # This MUST go after authenticated :user route

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/bowls/no_scraps', to: 'bowls#no_scraps', as: 'no_scraps'
  get '/scraps/no_bowls', to: 'scraps#no_bowls', as: 'no_bowls'
  
  resources :scraps

  resources :bowls do
    resources :scraps, except: [:destroy]
  end

  delete 'bowls/:bowl_id/scraps/:id', :to => 'bowls#remove_scrap_from_bowl'

  get '*path' => redirect('/')

end

app/models/bowl.rb
class Bowl < ActiveRecord::Base
  belongs_to :user
  has_many :bowl_scraps
  has_many :scraps, through: :bowl_scraps

  validates :name, presence: :true, :uniqueness => {scope: :user_id}, length: { maximum: 40 }
  validates :user, presence: :true

  accepts_nested_attributes_for :bowl_scraps

  scope :no_scraps, -> { Bowl.includes(:scraps).where( :scraps => { :id => nil } ) }

  def scraps_attributes=(scrap_attributes)
    scrap_attributes.delete_if { |_k, v| v[:description].blank? }
    scrap_attributes.values.each do |scrap_attribute|
      scrap = Scrap.find_or_create_by(description: scrap_attribute[:description], user_id: scrap_attribute[:user_id])
      self.bowl_scraps.build(scrap: scrap, priority: scrap_attributes["0"][:bowl_scraps_attributes]["0"][:priority])
    end
  end

end

app/controllers/bowls_controller.rb
class BowlsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bowl, only: [:show, :edit, :update, :destroy]

  def new
    @bowl = Bowl.new
  end

  def create
    @bowl = Bowl.new(bowl_params)

    if @bowl.save
      redirect_to @bowl
    else
      render :new
    end
  end

  def index
    @bowls = current_user.bowls.all
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @bowls }
    end
  end

  def show
    if @bowl.user != current_user
      redirect_to bowls_path
    else
      @scraps = @bowl.scraps
      @random = @scraps.sample
      respond_to do |format|
        format.html { render :show }
        format.json { render json: @bowl }
      end
    end
  end

  def edit
    redirect_to bowls_path if @bowl.user != current_user
  end

  def update
    if @bowl.user == current_user
      if @bowl.update(bowl_params)
        # If we don't set_bowl, instance variable @bowl.scraps will not contain newly
        # created scrap, even though database entry Bowl.find(id).scraps does have it
        set_bowl
        respond_to do |format|
          format.json { render json: @bowl, status: 200 }
          format.html { render :show }
        end
      else
        @bowl.restore_attributes(@bowl.errors.keys)
        render :edit
      end
    end
  end

  def destroy
    if @bowl.user == current_user
      @bowl.destroy
      redirect_to bowls_url
    end
  end

  def remove_scrap_from_bowl
    @bowl = Bowl.find(params[:bowl_id])
    scrap = @bowl.scraps.find(params[:id])

    if scrap
      @bowl.scraps.delete(scrap)
    end
    render json: @bowl, status: 200
  end

  def no_scraps
    @bowls = current_user.bowls.no_scraps
    render :index
  end

  private

  def bowl_params
    params.require(:bowl).permit(:name, :description, :user_id, scrap_ids:[], scraps_attributes: [:description, :user_id, bowl_scraps_attributes: [:priority]])
  end

  def set_bowl
    if !user_signed_in?
      redirect_to root_path
    else
      @bowl = Bowl.find(params[:id])
    end
    rescue ActiveRecord::RecordNotFound
      flash[:notice] = "bowl #{params[:id]} not found"
      redirect_to bowls_path
  end

end

app/helpers/bowls_helper.rb
module BowlsHelper
end

app/views/bowls/_bowl_form.html.erb
<% if !@bowl.errors[:name].empty? %>
  <div class="error_explanation">
    <%= @bowl.errors.full_messages_for(:name)[0].downcase %>
  </div>
<% else %>
  <%= f.label :name %> <span class="required">*</span>
<% end %>
<%= f.text_field :name, autocomplete: :off %></p>

<%= f.label :description %>
<%= f.text_field :description, autocomplete: :off %></p>

app/views/bowls/_scrap_form.html.erb
<%= f.fields_for :scraps, @bowl.scraps.build do |scraps_fields| %>
  <%= scraps_fields.hidden_field :user_id, value: current_user.id %>
  <%= scraps_fields.label :description, "scrap description" %>
  <%= scraps_fields.text_field :description, autocomplete: :off, required: true %></p>

  <%= scraps_fields.fields_for :bowl_scraps, @bowl.scraps.build.bowl_scraps.build do |bowl_scrap_form| %>
    <%= bowl_scrap_form.hidden_field :priority, value: nil %>
  <% end %>

<% end %>

app/views/bowls/edit.html.erb
<% title "edit #{@bowl.name}" %>

<div class="column">
  <h2>edit '<%= @bowl.name %>'</h2>

  <%= form_for @bowl do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= render 'bowl_form', f: f %>
    <%= f.submit %>
  <% end %>

  <p><%= link_to "delete bowl", @bowl, method: :delete, data: { confirm: "Delete bowl forever?" } %></p>

app/views/bowls/index.html.erb
<% title "bowls" %>

<div class="column">
    <%= link_to new_bowl_path, class: "random-bowl" do %>
      <div class="add-glyph">
        <div class="horizontal-line"></div>
        <div class="vertical-line"></div>
      </div>
      <%= link_to "new_bowl", new_bowl_path %>
    <% end %>
</div>

<% @bowls.each do |bowl| %>
  <div class="column">
      <%= link_to bowl_path(bowl), class: "random-bowl" do %>
        <div class="bowl-glyph"></div>
        <div class="bowl-name-div">

          <%= link_to bowl.name, bowl_path(bowl) %>
          </div>
      <% end %>
  </div>
<% end %> <!-- each do -->

app/views/bowls/new.html.erb
<% title "new bowl" %>

<div class="column">
  <h2>new bowl</h2>

  <%= form_for @bowl do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
    <%= render 'bowl_form', f: f %>
    <%= f.submit %>
  <% end %>
</div>

app/views/bowls/show.html.erb
<% title "#{@bowl.name}" %>

<div class="column" data-id="<%= @bowl.id %>">
  <div class="bowl-glyph">
    <% if !@bowl.scraps.empty? %>
      <%= link_to bowl_scrap_path(@bowl, @bowl.scraps.sample), class: "random-bowl" do %>
          <div class="bowl-fill">
            <div class="bowl-cta">
              pull a scrap
            </div> <!-- bowl-cta -->
          </div> <!-- bowl-fill -->
      <% end %>
    <% else %>
      <a class="random-bowl">
        <div class="bowl-fill">
          <div class="bowl-cta">
          </div>
        </div>
      </a>
    <% end %>
    </div> <!-- bowl-glyph -->

    <div class="bowl-name-div">
      <a class="previous">&#8249;</a>
      <h2 class="bowl-name"><%= @bowl.name %></h2>
      <a class="next">&#8250;</a>
    </div>

    <div>
      <div id="scrap-stuff">
        <p><a id="show-scraps-button">scraps</a></p>
        <div id="scraps" >
          <div id="display-scraps">
          </div>
          <!-- <button id="alphabetize">alphabetize</button> -->
          <div id="add-scraps" >
            <p><a id="add-scraps-button"><span id="plus">+</span></a></p>
            <div id="scraps-form">
              <%= form_for @bowl do |f| %>
                <%= render 'scrap_form', f: f %>
                <%= f.submit "add scrap", data: { disable_with: false } %>
              <% end %>
            </div> <!-- scraps-form -->
          </div> <!-- add-scraps -->
        </div> <!-- scraps -->
      </div> <!-- scrap-stuff -->
      <div id="bowl-stuff">
        <p><%= link_to "edit", edit_bowl_path, id: "edit-bowl" %></p>
      </div> <!-- bowl stuff -->
    </div>
</div>