config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'bowls#index', as: :authenticated_root
  end

  root 'home#index' # This MUST go after authenticated :user route

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/bowls/no_scraps', to: 'bowls#no_scraps', as: 'no_scraps'
  get '/scraps/no_bowls', to: 'scraps#no_bowls', as: 'no_bowls'
  
  resources :scraps

  resources :bowls do
    resources :scraps, except: [:destroy]
  end

  delete 'bowls/:bowl_id/scraps/:id', :to => 'bowls#remove_scrap_from_bowl'

  get '*path' => redirect('/')

end

app/models/scrap.rb
class Scrap < ActiveRecord::Base
  belongs_to :user
  has_many :bowl_scraps
  has_many :bowls, through: :bowl_scraps

  accepts_nested_attributes_for :bowl_scraps

  validates :description, presence: :true, uniqueness: {scope: :user_id}, length: { maximum: 140 }

  scope :no_bowls, -> { includes(:bowls).where( :bowls => { :id => nil } ) }

  def bowls_attributes=(bowl_attributes)
    bowl_attributes.delete_if { |_k, v| v[:name].blank? }
    bowl_attributes.values.each do |bowl_attribute|
      bowl = Bowl.find_or_create_by(name: bowl_attribute[:name], user_id: bowl_attribute[:user_id])
      self.bowl_scraps.build(bowl: bowl, priority: bowl_attributes["0"][:bowl_scraps_attributes]["0"][:priority])
    end
  end

end

app/controllers/scraps_controller.rb
class ScrapsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_scrap, only: [:show, :edit, :update, :destroy]
  before_action :set_bowl, only: [:new, :edit, :show, :index]

  def new
    if @bowl
      @scrap = Scrap.new(bowl_ids: [@bowl.id])
    else
      @scrap = Scrap.new
    end
  end

  def create
    @scrap = Scrap.new(scrap_params)
    if @scrap.save
      binding.pry
      redirect_to scrap_path(@scrap)
    else
      render :new
    end
  end

  def show
    if @scrap.user != current_user
      redirect_to scraps_path, alert: "scrap not found."
    elsif @bowl
      if !@scrap.bowls.include? @bowl
        redirect_to scraps_path, alert: "scrap not in that bowl."
      end
    else
      # render json: @scrap, status: 200
    end
  end

  def index
    if !@bowl
      @scraps = current_user.scraps.all
    else
      @scraps = @bowl.scraps
    end
    # render json: @scraps, status: 200
  end

  def edit
    redirect_to scraps_path if @scrap.user != current_user
    if @bowl
      if !@scrap.bowls.include? @bowl
        redirect_to scraps_path, alert: "scrap not in that bowl."
      elsif @scrap.nil?
        redirect_to bowl_scraps_path(@bowl), alert: "scrap not found."
      end
    end
  end

  def update
    if @scrap.update(scrap_params)
      if @scrap.save
        redirect_to scrap_path(@scrap)
      end
    else
      @scrap.restore_attributes(@scrap.errors.keys)
      render :edit
    end
  end

  def destroy
    @scrap.destroy
    redirect_to bowls_path
  end

  def no_bowls
    @scraps = current_user.scraps.no_bowls
    render :index
  end

  private

  def scrap_params
    params.require(:scrap).permit(:description, :category, :user_id, bowl_ids:[], bowls_attributes: [:name, :user_id, bowl_scraps_attributes: [:priority]])
  end

  def set_scrap
    @scrap = Scrap.find_by_id(params[:id])
    if !@scrap
      redirect_to scraps_path, alert: "scrap not found."
    end
  end

  def set_bowl
    if params[:bowl_id]
      @bowl = Bowl.find_by_id(params[:bowl_id])
      if !@bowl || @bowl.user != current_user
        redirect_to bowls_path, alert: "bowl not found."
      end
    end
  end

end

app/helpers/scraps_helper.rb
module ScrapsHelper
end

app/views/scraps/_form.html.erb
<%= f.hidden_field :user_id, :value => current_user.id %>

<% if !@scrap.errors[:description].empty? %>
  <div class="error_explanation">
    <%= @scrap.errors.full_messages_for(:description)[0].downcase %>
  </div>
<% else %>
  <%= f.label :description %> <span class="required">*</span>
<% end %>
<%= f.text_field :description, autocomplete: :off, maxlength: 140 %></p>

  add to existing bowl<br />
  <%= f.collection_check_boxes :bowl_ids, current_user.bowls, :id, :name %></p>

  <%= f.fields_for :bowls, @scrap.bowls.build do |bowls_fields| %>
    <%= bowls_fields.hidden_field :user_id, value: current_user.id %>
    <% if !@scrap.errors[:bowls].empty? %>
      <div class="error_explanation">
        <%= @scrap.errors.full_messages_for(:bowls)[0].downcase %>
      </div>
    <% else %>
      <%= bowls_fields.label :name, "add to new bowl" %>
    <% end %>
    <%= bowls_fields.text_field :name, autocomplete: :off %>

    <%= bowls_fields.fields_for :bowl_scraps, @scrap.bowls.build.bowl_scraps.build do |bowl_scrap_form| %>
      <%= bowl_scrap_form.hidden_field :priority, value: nil %>
    <% end %>
  <% end %>

<%= f.submit %>

app/views/scraps/edit.html.erb
<% title "edit #{@scrap.description}" %>

<div class="column">
  <h2>edit '<%= @scrap.description %>'</h2>

  <%= form_for @scrap do |f| %>
    <%= render 'form', f: f %>
  <% end %>

  <p><%= link_to "delete scrap", @scrap, method: :delete, data: { confirm: "Delete scrap from all bowls permanently?" } %></p>
</div>

app/views/scraps/index.html.erb
<% title "scraps" %>

<div class="column">
  <% if @bowl %>
    <h2>scraps in <%= link_to @bowl.name, bowl_path(@bowl) %></h2>
  <% else %>
    <h2>all scraps</h2>
  <% end %>

  <% if @bowl %>
    <% if @bowl.scraps.empty? %>
      <p>(this bowl is empty)</p>
      <p><%= link_to "add a scrap", new_bowl_scrap_path %></p>
    <% else %>
      <% @bowl.scraps.each do |scrap| %>
        <p>
          <%= scrap.description %>
          <%= link_to "(edit)", edit_scrap_path(scrap) %>
        </p>
      <% end %>
    <% end %>
  <% else %>
    <% if @scraps.empty? %>
      there are no scraps
      <p><%= link_to "make one", new_scrap_path %></p>
    <% else %>
      <% @scraps.each do |scrap| %>
        <p>
          <%= scrap.description %>
          <%= link_to "(edit)", edit_scrap_path(scrap) %>
        </p>
      <% end %>
    <% end %>
    <p><%= link_to "scraps with no bowl", no_bowls_path %></p>
  <% end %>

</div>

app/views/scraps/new.html.erb
<% title "new scrap" %>

<div class="column">
  <% if @bowl %>
    <h2>add scrap to '<%= @bowl.name %>'</h2>
  <% else %>
    <h2>new scrap</h2>
  <% end %>

  <%= form_for @scrap do |f| %>
    <%= render 'form', f: f %>
  <% end %>
</div>

app/views/scraps/show.html.erb
<% title @scrap.description %>


<div
  class="column"
  <% if @bowl %>
  data-id="<%= @bowl.id %>"
  <% end %>
  >
  <div class="scrap">
    <h2 class="scrap-h2" data-scrap-id="<%= @scrap.id %>">"<%= @scrap.description %>"</h2>
  </div>

  <% if @bowl %>
    <%= link_to "another", bowl_scrap_path(@bowl, @bowl.scraps.sample), class: "another" %>
    <p><%= link_to "edit", edit_bowl_scrap_path(@bowl, @scrap), class: "edit-scrap" %></p>
  <% else %>
    <p><%= link_to "edit", edit_scrap_path(@scrap), class: "edit-scrap" %></p>
  <% end %>
</div>

<!-- <script type="text/javascript" charset="utf-8">
  // Timer Function (possible future feature)
  var start = new Date();
  var startInSeconds = start.getMinutes()*60 + start.getSeconds();
  var timerTime = 60*5;
  var end = startInSeconds + timerTime;

  setInterval(function () {
    var now = new Date();
    var nowInSeconds = now.getMinutes()*60 + now.getSeconds();
    var remainingTime = end - nowInSeconds;
    var myResult = parseInt(remainingTime / 60) + ':' + remainingTime % 60;
      document.getElementById('my-timer').innerHTML = myResult;
  }, 500);
</script> -->