config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root :to => 'bowls#index', as: :authenticated_root
  end

  root 'home#index' # This MUST go after authenticated :user route

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get '/bowls/no_scraps', to: 'bowls#no_scraps', as: 'no_scraps'
  get '/scraps/no_bowls', to: 'scraps#no_bowls', as: 'no_bowls'
  
  resources :scraps

  resources :bowls do
    resources :scraps, except: [:destroy]
  end

  delete 'bowls/:bowl_id/scraps/:id', :to => 'bowls#remove_scrap_from_bowl'

  get '*path' => redirect('/')

end

app/views/layouts/_header.html.erb
<input class="burger-check" id="burger-check" type="checkbox"><label for="burger-check" class="burger"></label>
<nav id="navigation1" class="navigation">
  <ul>
    <% if !user_signed_in? %>
      <li><%= link_to user_session_path, user_session_path %></li>
    <% else %>
      <li><%= link_to bowls_path, bowls_path %></li>
      <li><%= link_to new_bowl_path, new_bowl_path %></li>
      <li><%#= link_to scraps_path, scraps_path %></li>
      <li><%#= link_to new_scrap_path, new_scrap_path %></li>
      <li><%= link_to(destroy_user_session_path, destroy_user_session_path, method: :delete) %></li>
      <!-- Not sure what next line is trying to do -->
      <li><%#= link_to "/users/dalma", edit_user_registration_path(current_user) if current_user unless current_user && current_user.uid %></li>
      <li>user: <%= current_user.email %></li>
    <% end %> <!-- end if user_signed_in? -->
  </ul>
</nav>

<center>
  <h1><%= link_to 'BOWLS', root_path %></h1>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'favicon.ico' %>
  <title>BOWLS | <%= yield :title %></title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<body>
  <div class="header">
    <%= render 'layouts/header' %>
  </div>

  <div class="wrapper">
    <div class="error_explanation">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
    </div>

    <%= yield %>
  </div>

  <div class="signature">
    <span class="heart">&#9829;</span> <a href="http://www.dalmaboros.com" target="_blank">DB 2024</a>
  </div>

  <% if user_signed_in? %>
    <div class="log-in-out">
      <%= link_to("log out", destroy_user_session_path, method: :delete) %>
    </div>
  <% end %>

</body>
</html>